### ISSUE TITLE
Warning msg and new ver

### ISSUE THREAD

**Issue by zonexo** [jviquerat/drl_shape_optimization#4]
Hi,

I just tried it. There are some warning msg below. Are they normal:

```
****** Starting episode 0
***    Starting control 0
WARNING:root:Dolfin's XML is a legacy format. Consider using XDMF instead.
-2.465207003554415 -0.5213985274605915
good epoch; reward: 0.2115029393916301
****** Starting episode 1
***    Starting control 0
WARNING:root:Dolfin's XML is a legacy format. Consider using XDMF instead.
Building point search tree to accelerate distance queries.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
```
Also, has the new PBO been added into the current code? If not, will it be easier to update? Is there any guide on how it can be done?

Thanks!

**Comment by jerabaul29** [comment]
Are you using the docker container to run the code? :)

These seems to be only depreciation warnings, so not errors per se.

**Comment by zonexo** [comment]
yes, i'm using docker

**Comment by zonexo** [comment]
Also, has the new PBO been added into the current code? If not, will it be easier to update? Is there any guide on how it can be done?

**Comment by jviquerat** [comment]
Hi @zonexo,

- As said by @jerabaul29, the message is just a warning, so it should not be a problem
- The PBO algorithm is not included in the present code and is not planned to be. If you want to use it (which I strongly advise from a performance point of view), you can find it <a href="https://github.com/jviquerat/pbo>here</a>, and you can find simple environment examples <a href="https://github.com/jviquerat/pbo/tree/master/envs>here</a>. I may be adding a simple optimization case in a near future, depending on my workload in the following weeks
