### ISSUE TITLE
Using GPU in WSL with drl_shape_optimization

### ISSUE THREAD

**Issue by zonexo** [jviquerat/drl_shape_optimization#6]
Hi, I've got the docker file working. However, when I did a check, it says GPU not available.

So does this code uses GPU for its deep learning?

Or is it that GPU is not available when I'm using it in WSL with docker?

Thanks.

PS: I have other deep learning docker codes which work in WSL with GPU capability.

**Comment by jviquerat** [comment]
Hi,
Sorry, I never tried to train it with GPU, and I have very limited experience regarding GPU training on docker containers.

Best,
